version: "3.9"
services:
  event-service:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EVENT_SERVICE
      PGDATA: "/var/lib/postgresql/data/docker-data/event-service"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data