server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EVENT_SERVICE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.xml

  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write_dates_as_timestamps: false